name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Set up Flutter (Dart ≥3.10)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.8' # نسخه Flutter که Dart 3.10.x دارد

      # Cache dependencies for speed
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Generate Freezed & Isar code
      - name: Generate code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      # Analyze code
      - name: Analyze code
        run: flutter analyze

      # Run unit tests
      - name: Run tests
        run: flutter test
